### ISSUE TITLE
Two monitors not being detected

### ISSUE THREAD

**Issue by pstatonwx** [Crozzers/screen_brightness_control#39]
Hello! 

Thanks for making this awesome package. I'm trying to make a "movie mode" app and want to dim both displays. However, when I list the monitors, the return is just: [MSI MAG24C], but in reality, I have two of the these monitors. 

Is there a current issue/bug if both monitors are named the same?

**Comment by Crozzers** [comment]
It sounds like the second monitor is being filtered out as a duplicate, which usually happens if it reports the same info as the first (EDID, serial, etc).

You should be able to use the `allow_duplicates` kwarg in the meantime to control both monitors, or you can set it as a global flag like so:
```python
import screen_brightness_control as sbc
sbc.config.ALLOW_DUPLICATES = True
```

Could you run the following snippet of code and send the output and `test.log` file that will be created? This should spit out a whole bunch of debugging info so that we can check if both monitors are detected correctly
```python
import screen_brightness_control as sbc
from pprint import pprint
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
pprint(sbc.debug_info())
```

**Comment by pstatonwx** [comment]
Okay that worked! Thank you so much!
